SELECT TOP (1000) [id]
      ,[date]
      ,[faculty]
      ,[parent_name]
      ,[student_id]
      ,[student_name]
      ,[subject]
      ,[write]
      ,[consent_prefix]
      ,[major]
      ,[prefix]
      ,[relationship]
      ,[sign]
      ,[student_prefix]
      ,[year]
      ,[reason]
      ,[argument]
  FROM [CS261-group7-650001].[dbo].[form]
